# Generated by Django 5.2 on 2026-05-12 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_pdf', models.FileField(upload_to='pdfs/original/')),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/signed/')),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('signature', models.TextField(blank=True)),
                ('public_key', models.TextField(blank=True)),
                ('private_key', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('signed', 'Signed'), ('verified', 'Verified'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('verification_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
