# Generated by Django 5.2 on 2026-05-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaldocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('hashed', 'Hash Generated'), ('signed', 'Signed'), ('verified', 'Verified'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
