# Generated by Django 5.2 on 2026-05-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_sign', '0002_alter_digitaldocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaldocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
